# Generated by Django 4.0 on 2022-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_address',
            field=models.CharField(default='7835 00300', max_length=255),
            preserve_default=False,
        ),
    ]
