# Generated by Django 4.0 on 2022-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_address',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='gkljke4', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
