# Generated by Django 4.0 on 2022-10-02 13:31

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='/profile/none.jpg', null=True, upload_to=store.models.profile_upload_path),
        ),
    ]
