# Generated by Django 4.0 on 2022-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
