# Generated by Django 4.0 on 2022-10-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_order_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
