# Generated by Django 4.0 on 2022-09-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20220901_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
