# Generated by Django 4.0.6 on 2022-09-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
